export const stationOne = {
  id: 3004,
  name: 'Municipal Services Building Plaza',
  coordinates: [
    -75.16374,
    39.95378,
  ],
  totalDocks: 30,
  docksAvailable: 20,
  bikesAvailable: 10,
  classicBikesAvailable: 10,
  smartBikesAvailable: 0,
  electricBikesAvailable: 0,
  rewardBikesAvailable: 10,
  rewardDocksAvailable: 20,
  kioskStatus: 'FullService',
  kioskPublicStatus: 'Active',
  kioskConnectionStatus: 'Active',
  kioskType: 1,
  addressStreet: '1401 John F. Kennedy Blvd.',
  addressCity: 'Philadelphia',
  addressState: 'PA',
  addressZipCode: '19102',
  bikes: [
    {
      dockNumber: 1,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 2,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 6,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 14,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 16,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 19,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
  ],
  closeTime: undefined,
  eventEnd: undefined,
  eventStart: undefined,
  isEventBased: false,
  isVirtual: false,
  kioskId: 3004,
  notes: undefined,
  openTime: undefined,
  publicText: '',
  timeZone: undefined,
  trikesAvailable: 0,
  latitude: '39.95378',
  longitude: '-75.16374',
  createdAt: new Date('2021-05-08T16:48:10.997Z'),
};

export const stationTwo = {
  id: 3005,
  name: 'Welcome Park, NPS',
  coordinates: [
    -75.14403,
    39.94733,
  ],
  totalDocks: 30,
  docksAvailable: 20,
  bikesAvailable: 10,
  classicBikesAvailable: 10,
  smartBikesAvailable: 0,
  electricBikesAvailable: 0,
  rewardBikesAvailable: 10,
  rewardDocksAvailable: 20,
  kioskStatus: 'FullService',
  kioskPublicStatus: 'Active',
  kioskConnectionStatus: 'Active',
  kioskType: 1,
  addressStreet: '1401 John F. Kennedy Blvd.',
  addressCity: 'Philadelphia',
  addressState: 'PA',
  addressZipCode: '19102',
  bikes: [
    {
      dockNumber: 1,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 2,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 6,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 14,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 16,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
    {
      dockNumber: 19,
      isElectric: false,
      isAvailable: true,
      battery: undefined,
    },
  ],
  closeTime: undefined,
  eventEnd: undefined,
  eventStart: undefined,
  isEventBased: false,
  isVirtual: false,
  kioskId: 3005,
  notes: undefined,
  openTime: undefined,
  publicText: '',
  timeZone: undefined,
  trikesAvailable: 0,
  latitude: '39.94733',
  longitude: '-75.14403',
  createdAt: new Date('2021-05-09T16:48:10.997Z'),
};

export const weatherOne = {
  dt: 1620345600,
  sunrise: 1620294870,
  sunset: 1620345597,
  temp: 288.98,
  feels_like: 284.47,
  pressure: 1013,
  humidity: 34,
  dew_point: 273.16,
  uvi: 6.62,
  clouds: 75,
  visibility: 16093,
  wind_speed: 3.6,
  wind_deg: 360,
  weather: [
    {
      id: 803,
      main: 'Clouds',
      description: 'broken clouds',
      icon: '04n',
    },
  ],
};
